"""FSM state definitions and transition rules."""

from __future__ import annotations

PLAN_FLOW_STATES = {
    "PLAN_FLOW:DATA_COLLECTION",
    "PLAN_FLOW:CONFIRMATION_PENDING",
    "PLAN_FLOW:FINALIZATION",
}

ADAPTATION_SELECTION = "ADAPTATION_SELECTION"
ADAPTATION_PARAMS = "ADAPTATION_PARAMS"
ADAPTATION_CONFIRMATION = "ADAPTATION_CONFIRMATION"

ADAPTATION_FLOW_STATES = {
    ADAPTATION_SELECTION,
    ADAPTATION_PARAMS,
    ADAPTATION_CONFIRMATION,
}

ADAPTATION_FLOW_ALLOWED_TRANSITIONS = {
    ("ACTIVE", ADAPTATION_SELECTION),
    ("ACTIVE_PAUSED", ADAPTATION_SELECTION),
    (ADAPTATION_SELECTION, ADAPTATION_PARAMS),
    (ADAPTATION_SELECTION, ADAPTATION_CONFIRMATION),
    (ADAPTATION_SELECTION, "ACTIVE"),
    (ADAPTATION_PARAMS, ADAPTATION_CONFIRMATION),
    (ADAPTATION_PARAMS, "ACTIVE"),
    (ADAPTATION_CONFIRMATION, "ACTIVE"),
    (ADAPTATION_CONFIRMATION, ADAPTATION_PARAMS),
}

PLAN_FLOW_ALLOWED_TRANSITIONS = {
    ("PLAN_FLOW:DATA_COLLECTION", "PLAN_FLOW:CONFIRMATION_PENDING"),
    ("PLAN_FLOW:CONFIRMATION_PENDING", "PLAN_FLOW:FINALIZATION"),
    ("PLAN_FLOW:CONFIRMATION_PENDING", "PLAN_FLOW:DATA_COLLECTION"),
}

ACTIVE_CONFIRMATION_ENTRYPOINTS = set()
ACTIVE_PAUSED_CONFIRMATION_ENTRYPOINTS = set()

ADAPTATION_FLOW_ENTRY_STATES = {
    "ACTIVE",
    "ACTIVE_PAUSED",
}

PLAN_FLOW_ENTRYPOINTS = {
    "IDLE_ONBOARDED",
    "IDLE_FINISHED",
    "IDLE_DROPPED",
    "IDLE_PLAN_ABORTED",
    "ACTIVE",
    "ACTIVE_PAUSED",
}

IDLE_STATES = {
    "IDLE_NEW",
    "IDLE_ONBOARDED",
    "IDLE_PLAN_ABORTED",
    "IDLE_FINISHED",
    "IDLE_DROPPED",
}

ACTIVE_STATES = {
    "ACTIVE",
    "ACTIVE_CONFIRMATION",
    "ACTIVE_PAUSED_CONFIRMATION",
}

PAUSE_STATES = {
    "ACTIVE_PAUSED",
}

ALLOWED_BASE_STATES = IDLE_STATES | ACTIVE_STATES | PAUSE_STATES

PREFIXED_STATES = {"PLAN_FLOW"}

FSM_ALLOWED_STATES = (
    ALLOWED_BASE_STATES
    | PLAN_FLOW_STATES
    | ADAPTATION_FLOW_STATES
)

PLAN_AGENT_ALLOWED_TRANSITION_SIGNALS = PLAN_FLOW_STATES | {
    ADAPTATION_SELECTION,
    ADAPTATION_PARAMS,
    ADAPTATION_CONFIRMATION,
    "EXECUTE_ADAPTATION",
    "ACTIVE_CONFIRMATION",
    "ACTIVE_PAUSED_CONFIRMATION",
    "ACTIVE_PAUSED",
    "ACTIVE",
    "IDLE_PLAN_ABORTED",
}
