ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS goal TEXT;
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS duration_days INTEGER;
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS send_hour INTEGER;
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS send_minute INTEGER;
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS tasks_per_day INTEGER;
