BEGIN;

ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS activated_at TIMESTAMP;
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS current_day INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS duration VARCHAR(20);
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS focus VARCHAR(20);
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS load VARCHAR(20);
ALTER TABLE ai_plans ADD COLUMN IF NOT EXISTS total_days INTEGER;

COMMIT;
